config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'

  resources :posts do
    resources :comments
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    post_id = params[:post_id]

    comment = Comment.new
    comment.detail = params[:detail]
    comment.post_id = post_id

    if comment.save
      flash[:success] = "댓글을 쓰셨습니다!"
      redirect_to '/posts/' + post_id + '/'
    else
      flash[:alert] = "댓글 생성에 실패하였습니다!"
      redirect_to '/posts/' + post_id + '/'
    end
  end

  def update
    comment = Comment.find(params[:comment_id])
    comment.detail = params[:detail]

    if comment.update
      flash[:success] = "댓글을 수정하셨습니다!"
      redirect_to '/posts/' + post_id + '/'
    else
      flash[:alert] = "댓글 수정에 실패하였습니다!"
      redirect_to '/posts/' + post_id + '/'
    end
  end

  def destroy
    comment = Comment.find(params[:comment_id])

    if comment.destroy
      flash[:success] = "댓글을 삭제하셨습니다!"
      redirect_to '/posts/' + post_id + '/'
    else 
      flash[:alert] = "댓글 삭제에 실패하셨습니다!"
      redirect_to '/posts/' + post_id + '/'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
  end

  def create
    post = Post.new(post_params)
   
    if post.save
      flash[:success] = "게시글을 생성하셨습니다!"
      redirect_to posts_path
    else
      flash[:alert] = "게시글 생성에 실패하였습니다!"
      redirect_to posts_path
    end
  end

  def show
    post = post_by_id

    @title = post.title
    @detail = post.detail
  end

  def edit
    @post = post_by_id
  end

  def update
    post = post_by_id
    
    if post.update(post_params)
      flash[:success] = "게시글을 수정하셨습니다!"
      redirect_to post_path(post)
    else
      flash[:alert] = "게시글 수정에 실패하였습니다!"
      redirect_to post_path(post)
    end
end

  def destroy
    post = post_by_id
    
    if post.destroy
      flash[:success] = "게시글을 삭제하셨습니다!"
      redirect_to posts_path
    else
      flash[:alert] = "게시글 삭제에 실패하였습니다!"
      redirect_to posts_path
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :detail)
  end

  def post_by_id
    Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardAssignment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
  
</html>

app/views/posts/edit.html.erb
<div class="container" style="margin-top: 50px;">
    <h2>글쓰기 페이지</h2>
    <%= form_for(@post) do |f| %>
        <%= f.text_field(:title, value: @post.title, size: 30, placeholder: "제목", class: "form-control") %><br>
        <%= f.text_area(:detail, value: @post.detail, size: "30x15", placeholder: "내용", class: "form-control") %><br>
        <div class="row">
            <div class="col-md-2">
                <%= link_to "뒤로 가기", posts_path, class: "btn btn-default btn-lg btn-blick" %>
            </div>
            <div class="col-md-2 col-md-offset-8">
                <%= f.submit("수정하기", class: "btn btn-success btn-lg btn-block") %>
            </div>
        </div>
    <% end %>
</div>

app/views/posts/index.html.erb
<div class="container" style="margin-top: 50px;">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <a href="/posts/new" class="btn btn-success btn-lg btn-block" role="button">글쓰기</a>
    </div>
  </div>

  <div class="row" style="margin-top: 30px;">
    <div class="col-md-8 col-md-offset-2">
      <table class="table table-hover">
        <thead>
          <tr>
            <th width="100">게시글 번호</th>
            <th>게시글 제목</th>
            <th width="50"></th>
            <th width="50"></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td>
              <%= post.id %>
            </td>
            <td>
              <%= link_to post.title, post_path(post) %>
            </td>
            <td>
              <%= link_to '', edit_post_url(post), method: 'get', class: 'glyphicon glyphicon-edit' %>
            </td>
            <td>
              <%= link_to '', post_url(post), method: 'delete', class: "glyphicon glyphicon-remove", remote: true, data: { confirm: "정말 삭제하시겠습니까?" } %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container" style="margin-top: 50px;">
    <h2>글쓰기 페이지</h2>
    <%= form_tag(controller: "posts", action: "create", method: "post") do %>
        <%= text_field(:post, :title, size: 30, placeholder: "제목", class: "form-control") %><br>
        <%= text_area(:post, :detail, size: "30x15", placeholder: "내용", class: "form-control") %><br>
        <div class="row">
            <div class="col-md-2">
                <%= link_to "뒤로 가기", posts_path, class: "btn btn-default btn-lg btn-blick" %>
            </div>
            <div class="col-md-2 col-md-offset-8">
                <%= submit_tag("글쓰기", class: "btn btn-success btn-lg btn-block") %>
            </div>
        </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="container" style="margin-top: 50px;">
    <h2>상세 보기 페이지</h2>
    <%= text_field_tag(:title, @title, size: 30, placeholder: "제목", class: "form-control", disabled: true) %><br>
    <%= text_area_tag(:detail, @detail, size: "30x15", placeholder: "내용", class: "form-control", disabled: true) %><br>
    <div class="row">
        <div class="col-md-2">
            <%= link_to "뒤로 가기", posts_path, class: "btn btn-default btn-lg btn-blick" %>
        </div>
    </div>
</div>